#!/bin/sh

### BEGIN INIT INFO
# Provides:           kernelsoa_pr_montecerrado
# Required-Start:     $local_fs $network $syslog mysql
# Required-Stop:      $local_fs $network $syslog
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  kernelsoa_pr_montecerrado
# Description:        kernelsoa_pr_montecerrado
### END INIT INFO

NAME="kernelsoa_pr_montecerrado"
PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
APPDIR="/home/soa/sistema_pr_montecerrado/kernelsoa_unitpbd_v2/kernel"
APPBIN="/home/soa/sistema_pr_montecerrado/kernelsoa_unitpbd_v2/kernel/kernelsoa"
APPARGS="sistema_pr_montecerrado"
USER="root"
GROUP="root"

# pid file for the daemon
PIDFILE="/var/run/kernelsoa_pr_montecerrado.pid"

# Include functions 
set -e
. /lib/lsb/init-functions

start() {
   printf "Starting '$NAME'... "
   start-stop-daemon --start --chuid "$USER:$GROUP" --background --chdir "$APPDIR" --exec "$APPBIN" -- $APPARGS || true
   printf "done\n"
}


stop() {
  printf "Stopping '$NAME'... "
  kill -9 `cat $PIDFILE`
  printf "done\n"
}

status() {
  # Check the status of the process.
  if [ -e $PIDFILE ]; then
    status_of_proc -p $PIDFILE $APPBIN "$NAME process" && exit 0 || exit $?
  else
    log_daemon_msg "$NAME Process is not running"
    log_end_msg 0
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $NAME {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
