
--
-- Table structure for table `permisos`
--

DROP TABLE IF EXISTS `permisos`;

CREATE TABLE `permisos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nemo` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

insert into permisos (nemo) VALUES
('Ver programación riego'),
('Ver programación riego histórico'),
('Programar riego añadir'),
('Programar riego anular'),
('Programar riego modificar'),
('Ver programación depuración'),
('Ver programación depuración histórico'),
('Programar depuración añadir'),
('Programar depuración anular'),
('Programar depuración modificar'),
('Hoy añadir sesiones'),
('Hoy activación manual'),
('Ambiente ver'),
('Ambiente modificar'),
('Rutina ver'),
('Rutina modificar'),
('Escena ver'),
('Escena modificar'),
('Estado vivienda ver'),
('Estado vivienda modificar'),
('Solar'),
('Eficiencia'),
('Consumos'),
('Consumos Luz'),
('Consumos Agua'),
('Consumos Gas'),
('Seguridad'),
('Galeria'),
('Ekeeper'),
('Camaras'),
('Cuadro Eléctrico'),
('Red agua'),
('Climatización'),
('RCs'),
('Alarmas'),
('Notificaciones'),
('Tareas'),
('Compras'),
('Post'),
('Avisos'),
('Personal'),
('Equipos'),
('Documentos'),
('Crear Escenas'),
('Crear Rutina'),
('Sostenibilidad'),
('Accesos'),
('Control Home'),
('Control System'),
('Comunicaciones'),
('Modificar Escena Maxima'),
('Modificar Escena Stadar'),
('Cambio Contraseña'),
('Scanner'),
('Camara liveKit'),
('Ambiente ver Grupo'),
('Ambiente modificar Grupo'),
('Rutina ver Grupo'),
('Rutina modificar Grupo'),
('Apagar/Encender General Luces'),
('Apagar/Encender General Clima'),
('Apagar/Encender General IOT'),
('Apagar/Encender General Estores'),
('Configurar General Estancias A/E');
