#!/bin/sh

### BEGIN INIT INFO
# Provides:           soaraspberry
# Required-Start:     $local_fs $network $syslog
# Required-Stop:      $local_fs $network $syslog
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  soaraspberry
# Description:        soaraspberry
### END INIT INFO

NAME="soaraspberry"
PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
APPDIR="/"
APPBIN="/home/soa/soaraspberry/soaraspberry.elf"
APPARGS=""
USER="root"
GROUP="root"

# Include functions 
set -e
. /lib/lsb/init-functions

start() {
   printf "Starting '$NAME'... "
   start-stop-daemon --start --chuid "$USER:$GROUP" --background --chdir "$APPDIR" --exec "$APPBIN" -- $APPARGS || true
   printf "done\n"
}


stop() {
  printf "Stopping '$NAME'... "
  kill $(pgrep $NAME)
  printf "done\n"
}

status() {
  status_of_proc $NAME && exit 0 || exit $?
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $NAME {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0

