DROP TABLE IF EXISTS empresas;
CREATE TABLE empresas (
      `_idempresas` int(11) NOT NULL AUTO_INCREMENT,
      `fecha` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
      `tipotcaso` varchar(155) DEFAULT NULL,   
      `sector` varchar(155) DEFAULT NULL,
      `empresa` varchar(155) DEFAULT NULL,
      `ciudad` varchar(155) DEFAULT NULL,
      `numempleados` varchar(55) DEFAULT NULL,
      `ceo_director` varchar(155) DEFAULT NULL,
      `nombre` varchar(155) DEFAULT NULL,
      `apellidos` varchar(155) DEFAULT NULL,
      `cargo` varchar(155) DEFAULT NULL,
      `cif` varchar(155) DEFAULT NULL,
      PRIMARY KEY (`_idempresas`));

INSERT INTO empresas VALUES 
   (1,now(),'empresa','abogados','Arriaga Asociados','Madrid','615','Antonio Queraltó Velasco','Antonio','Queraltó Velasco','CEO/Director','0000001'),
   (2,now(),'empresa','abogados','BDO Abogados y Asesores Tributarios','Madrid','330','Enrique Azorín','Enrique','Azorín','CEO/Director','0000002'),
   (3,now(),'empresa','abogados','Clifford Chance','Madrid','234','Jaime Velázquez','Jaime','Velázquez','CEO/Director','0000003'),
   (4,now(),'empresa','abogados','Cuatrecasas','Madrid','1580','Jorge Badía','Jorge','Badía','CEO/Director','0000004'),
   (5,now(),'empresa','abogados','Dac Beachcroft','Madrid','1100','Gustavo Blanco','Gustavo','Blanco','CEO/Director','0000005'),
   (6,now(),'empresa','abogados','Deloitte Legal','Madrid','716','Luis Fernando Guerra','Luis Fernando','Guerra','CEO/Director','0000006'),
   (7,now(),'empresa','abogados','Garrigues','Madrid','2045','Fernando Vives','Fernando','Vives','CEO/Director','0000007'),
   (8,now(),'empresa','abogados','KPMG Abogados','Madrid','784','Alberto Estrelles','Alberto','Estrelles','CEO/Director','0000008'),
   (9,now(),'empresa','abogados','Pons','Madrid','315','Ignacio Sevilla','Ignacio','Sevilla','CEO/Director','0000009'),
   (10,now(),'empresa','abogados','Pons IP','Madrid','127','Nuria Marcos Herrezuelo','Nuria','Marcos Herrezuelo','CEO/Director','0000010'),
   (11,now(),'empresa','abogados','PWC TAX & Legal Services','Madrid','957','Gonzalo Sánchez','Gonzalo','Sánchez','CEO/Director','0000011'),
   (12,now(),'empresa','abogados','Roca Junyent','Barcelona','220','Joan Roca','Joan','Roca','CEO/Director','0000012'),
   (13,now(),'empresa','abogados','Uría Menendez','Madrid','969','Luis de Carlos Bertrán','Luis de Carlos','Bertrán','CEO/Director','0000013'),
   (14,now(),'empresa','aerolíneas','IAG','Madrid','63422','Willie Walsh','Willie','Walsh','CEO/Director','0000014'),
   (15,now(),'empresa','aeronáutica','Airbus Group','Getafe','59000','Fernando Alonso','Fernando','Alonso','CEO/Director','0000015'),
   (16,now(),'empresa','aeronáutica','Industria de Turbo Propulsores (ITP)','Zamudio','3000','Josep Piqué','Josep','Piqué','CEO/Director','0000016'),
   (17,now(),'empresa','alimentacion y bebidas','Calidad Pascual','Madrid','2159','Ignacio García-Cano','Ignacio','Garcia-Cano','CEO/Director','0000017'),
   (18,now(),'empresa','alimentacion y bebidas','Campofrío Food Group','Alcobendas','7222','Ricardo Doehner','Ricardo','Doehner','CEO/Director','0000018'),
   (19,now(),'empresa','alimentacion y bebidas','Coca-Cola European Partners','Madrid','23500','Francesc Cosano','Francesc','Cosano','CEO/Director','0000019'),
   (20,now(),'empresa','alimentacion y bebidas','Damm','Barcelona','4000','Enric Crous i Millet','Enric','Crous i Millet','CEO/Director','0000020'),
   (21,now(),'empresa','alimentacion y bebidas','Ebro Food','Madrid','6195','Antonio Hernández Callejas','Antonio','Hernández Callejas','CEO/Director','0000021'),
   (22,now(),'empresa','alimentacion y bebidas','Heineken España','Sevilla','2471','Richard Wissend','Richard','Wissend','CEO/Director','0000022'),
   (23,now(),'empresa','alimentacion y bebidas','Mahou-San Miguel','Madrid','3200','Alberto Rodríguez-Toquero','Alberto','Rodríguez-Toquero','CEO/Director','0000023'),
   (24,now(),'empresa','alimentacion y bebidas','Nestlé España','Esplugues de Llobregat','1800','Jacques Reber','Jacques','Reber','CEO/Director','0000024'),   
   (25,now(),'empresa','alimentacion y bebidas','Pepsico Iberia','Barcelona','3000','Ramón Laguarta','Ramón','Laguarta','CEO/Director','0000025'),
   (26,now(),'empresa','auditoría','Deloitte','Madrid','8000','Luis Fernando Guerra','Luis Fernando','Guerra','CEO/Director','0000026'),
   (27,now(),'empresa','auditoría','KPMG','Madrid','3770','Ignacio Faus','Ignacio','Faus','CEO/Director','0000027'),
   (28,now(),'empresa','automoción','KIA Motors Iberia','Alcobendas','40000','Eduardo Divar','Eduardo','Divar','CEO/Director','0000028'),
   (29,now(),'empresa','automoción','Mercedes-Benz España','Alcobendas','5500','Reiner Hoeps','Reiner','Hoeps','CEO/Director','0000029'),
   (30,now(),'empresa','automoción','Peugeot España','Madrid','','Jorge Tomé','Jorge','Tomé','CEO/Director','0000030'),
   (31,now(),'empresa','automoción','Seat','Martorell','13000','Luca de Meo','Luca','de Meo','CEO/Director','0000031'),
   (32,now(),'empresa','automoción','Sernauto','Madrid','330000','José Portilla Gonzalez','José','Portilla Gonzalez','CEO/Director','0000032'),
   (33,now(),'empresa','autopistas y aparcamientos','Abertis Infraestructuras','Madrid','15099','José Aljaro Navarro','José','Aljaro Navarro','CEO/Director','0000033'),
   (34,now(),'empresa','auxiliar del automovil','Federal Mogul España','Coslada','50000','David Zapata','David','Zapata','CEO/Director','0000024'),
   (35,now(),'empresa','auxiliar del automovil','Ficosa','Barcelona','10000','Javier Pujol Artigas','Javier','Pujol Artigas','CEO/Director','0000035'),
   (36,now(),'empresa','auxiliar del automovil','Gestamp','Madrid','41000','Francisco José Riberas Mera','Francisco José','Riberas Mera','CEO/Director','0000036'),
   (37,now(),'empresa','bancos y ent. de crédito','Banco Santander','Boadilla del Monte','200961','José Antonio Álvarez','José Antonio','Álvarez','CEO/Director','0000037'),
   (38,now(),'empresa','bancos y ent. de crédito','Caixabank','Valencia','36972','Gonzalo Gortázar','Gonzalo','Gortázar','CEO/Director','0000038'),
   (39,now(),'empresa','bancos y ent. de crédito','HSBC Bank Sucursal en España','Madrid','229000','John Flint','John','Flint','CEO/Director','0000039'),
   (40,now(),'empresa','bancos y ent. de crédito','Liberbank','Madrid','4139','Manuel Menéndez','Manuel','Menéndez','CEO/Director','0000040'),
   (41,now(),'empresa','bienes de eq. electrico','Cobra (grupo)','Madrid','35530','Eugenio Llorente Gómez','Eugenio','Llorente Gómez','CEO/Director','0000041'),
   (42,now(),'empresa','construccion','Acciona','Alcobendas','37400','José Manuel Entrecanales','José Manuel','Entrecanales','CEO/Director','0000042'),
   (43,now(),'empresa','construccion','FCC','Madrid','57405','Pablo Colio Abril','Pablo','Colio Abril','CEO/Director','0000043'),
   (44,now(),'empresa','construccion','Grupo ACS','Madrid','182269','Marcelino Fernández','Marcelino','Fernández','CEO/Director','0000044'),
   (45,now(),'empresa','construccion','Sacyr','Madrid','30309','Manuel Manrique','Manuel','Manrique','CEO/Director','0000045'),
   (46,now(),'empresa','construcciones mecánicas','Construcciones y Auxiliar de Ferrocarriles (CAF)','Beasaín','8428','Andrés Arizcorreta García','Andrés','Arizcorreta García','CEO/Director','0000046'),
   (47,now(),'empresa','consultoría','Accenture','Madrid','12000','Jose Luis Sancho','Jose Luis','Sancho','CEO/Director','0000047'),
   (48,now(),'empresa','distribución','Auchan Retail España','Madrid','20200','Pedro Alonso Villoslada','Pedro','Alonso Villoslada','CEO/Director','0000048'),
   (49,now(),'empresa','distribución','Centros Comercial Carrefour','Madrid','53000','Eric Uzan','Eric','Uzan','CEO/Director','0000049'),
   (50,now(),'empresa','distribución','Decathlon España','San Sebastian de los Reyes','12322','Javier López Segovia','Javier','López Segovia','CEO/Director','0000050'),
   (51,now(),'empresa','distribución','Eroski','Elorrio','33816','Javier Amezaga Salazar','Javier','Amezaga Salazar','CEO/Director','0000051'),
   (52,now(),'empresa','distribución','Grupo El Corte Inglés','Madrid','92078','Jesús Nuño de la Rosa','Jesús','Nuño de la Rosa','CEO/Director','0000052'),
   (53,now(),'empresa','distribución','Grupo IFA','Alcobendas','103365','Roberto Tojeiro','Roberto','Tojeiro','CEO/Director','0000053'),
   (54,now(),'empresa','distribución','Leroy Merlin','Alcobendas','10659','Ignacio Sánchez','Ignacio','Sánchez','CEO/Director','0000054'),
   (55,now(),'empresa','distribución','Lidl','Montcada i Reixac','13000','Claus Grande','Claus','Grande','CEO/Director','0000055'),
   (56,now(),'empresa','distribución','Mercadona','Tavernes Blanques','84000','José Jordá','José','Jordá','CEO/Director','0000056'),
   (57,now(),'empresa','editoriales','Santillana','Tres Cantos','3906','Miguel Ángel Cayuela','Miguel Ángel','Cayuela','CEO/Director','0000057'),
   (58,now(),'empresa','electrodomésticos','Electrolux España','Alcobendas','159','Ramón Sariego-Villar','Ramón','Ramón Sariego-Villar','CEO/Director','0000058'),
   (59,now(),'empresa','energía y agua','Cepsa','Madrid','9800','Pedro Miró','Pedro','Miró','CEO/Director','0000059'),
   (60,now(),'empresa','energía y agua','Endesa','Madrid','9706','José Bogas','José','Bogas','CEO/Director','0000060'),
   (61,now(),'empresa','energía y agua','Iberdrola','Madrid','33772','Ángeles Santamaría Martín','Ángeles','Santamaría Martín','CEO/Director','0000061'),
   (62,now(),'empresa','energía y agua','Repsol','Madrid','24352','Josu Jon Imaz','Josu','Jon Imaz','CEO/Director','0000062'),
   (63,now(),'empresa','energía y agua','Siemens Gamesa','Zamudio','Más de 25000','Markus Tacke','Markus','Tacke','CEO/Director','0000063'),
   (64,now(),'empresa','ingeniería','Elecnor','Madrid','13144','Rafael Martín de Bustamante','Rafael','Martín de Bustamante','CEO/Director','0000064'),
   (65,now(),'empresa','limpieza','Clece','Madrid','74711','Cristóbal Valderas Alvarado','Cristóbal','Valderas Alvarado','CEO/Director','0000065'),
   (66,now(),'empresa','limpieza','Eulen Limpieza','Madrid','17653','Mª José Álvarez Mezquiriz','Mº José','Álvarez Mezquiriz','CEO/Director','0000066'),
   (67,now(),'empresa','madera y muebles','IKEA Ibérica','San Sebastián de los Reyes','8676','Petra Axdorff','Petra','Axdorff','CEO/Director','0000067'),
   (68,now(),'empresa','medios de comunicacion','Corporacion RTVE','Pozuelo de Alarcon','6400','Federico Montero','Federico','Montero','CEO/Director','0000068'),
   (69,now(),'empresa','medios de comunicacion','Prisa (Grupo)','Tres Cantos','8643','Manuel Mirat','Manuel','Mirat','CEO/Director','0000069'),
   (70,now(),'empresa','medios de pago','Mastercard España','Madrid','12000','Ovidio Egido','Ovidio','Egido','CEO/Director','0000070'),
   (71,now(),'empresa','moda y complementos','Hennes & Mauritz (H&M)','Barcelona','Mas de 171000','Ralf Wein','Ralf','Wein','CEO/Director','0000071'),
   (72,now(),'empresa','moda y complementos','Inditex','Arteixo','171839','Pablo Isla','Pablo','Isla','CEO/Director','0000072'),
   (73,now(),'empresa','ocio y cultura','Grupo Mediapro','Barcelona','6500','Jonathan Cumming','Jonathan','Cumming','CEO/Director','0000073'),   
   (74,now(),'empresa','restauración','Restaurant Brands Iberia (Burguer King)','Pozuelo de Alarcón','17500','Gregorio Jiménez','Gregorio','Jiménez','CEO/Director','0000074'),
   (75,now(),'empresa','restauración','Serunion','Barcelona','Mas de 20500','Antonio Llorens Tubau','Antonio','Llorens Tubau','CEO/Director','0000075'),
   (76,now(),'empresa','restauración','Telepizza','San Sebastián de los Reyes','5515','Pablo Juantegui Azpilicueta','Pablo','Juantegui Azpilicueta','CEO/Director','0000076'),
   (77,now(),'empresa','sanidad privada','Quirón Salud','Madrid','3500','Héctor Ciria','Héctor','Ciria','CEO/Director','0000077'),
   (78,now(),'empresa','sanidad privada','Sanitas','Madrid','11225','Iñaki Ereño','Iñaki','Ereño','CEO/Director','0000078'),
   (79,now(),'empresa','seguridad','Prosegur','Madrid','175000','Helena Revoredo','Helena','Revoredo','CEO/Director','0000079'),
   (80,now(),'empresa','seguros','Aegon España','Madrid','450','Tomás Alfaro','Tomás','Alfaro','CEO/Director','0000080'),
   (81,now(),'empresa','seguros','Mapfre (Grupo)','Majadahonda','36372','José Manuel Inchausti Pérez','José Manuel','Inchausti Pérez','CEO/Director','0000081'),
   (82,now(),'empresa','seguros','Sanitas','Madrid','11225','Iñaki Ereño','Iñaki','Ereño','CEO/Director','0000082'),
   (83,now(),'empresa','seguros','Segurcaixa Adeslas','Madrid','5654','Javier Murillo','Javier','Murillo','CEO/Director','0000083'),
   (84,now(),'empresa','siderurgia y metaluergia','Acerinox','Madrid','6742','Bernardo Velázquez','Bernardo','Velázquez','CEO/Director','0000084'),
   (85,now(),'empresa','sociedades y ag.de valores','Renta 4 Banco','Madrid','490','Juan Carlos Ureta Domingo','Juan Carlos','Ureta Domingo','CEO/Director','0000085'),
   (86,now(),'empresa','telecomunicaciones','Telefónica','Madrid','117000','Ángel Vilá','Ángel','Vilá','CEO/Director','0000086'),
   (87,now(),'empresa','turismo','Amadeus IT Group','Madrid','15000','Luis Maroto','Luis','Maroto','CEO/Director','0000087'),
   (88,now(),'empresa','turismo','Barceló Corporación Empresarial','Palma de Mallorca','31768','Raúl Gonzalez','Raúl','Gonzalez','CEO/Director','0000088'),
   (89,now(),'empresa','turismo','Globalia','Llucmajor','14754','Javier Hidalgo','Javier','Hidalgo','CEO/Director','0000089'),
   (90,now(),'empresa','turismo','Grupo Iberostar','Palma de Mallorca','28000','Sabina Fluxá','Sabina','Fluxá','CEO/Director','0000090'),
   (91,now(),'empresa','turismo','Grupo Piñero','Murcia','14740','Encarnación Piñero','Encarnación','Piñero','CEO/Director','0000091'),
   (92,now(),'empresa','turismo','Meliá Hotels International','Palma de Mallorca','44761','Gabriel Escarrer Jaume','Gabriel','Escarrer Jaume','CEO/Director','0000092'),
   (93,now(),'empresa','turismo','NH Hotel Group','Madrid','22789','Ramón Aragonés Marín','Ramón','Aragonés Marín','CEO/Director','0000093'),
   (94,now(),'empresa','turismo','Palladium Hotel Group','Madrid','11633','Abel Matutes','Abel','Matutes','CEO/Director','0000094'),
   (95,now(),'empresa','turismo','Riu Hotels & Resorts','Palma de Mallorca','28894','Carmen Riu Güel','Carmen','Riu Güel','CEO/Director','0000095'),
   (96,now(),'empresa','otras empresas','Atento','Madrid','10000','José María Pérez Melber','José María','Pérez Melber','CEO/Director','0000096'),
   (97,now(),'empresa','otras empresas','Corporación Mondragón','Guipúzcoa','80818','Iñigo Ucín','Iñigo','Ucín','CEO/Director','0000097'),
   (98,now(),'empresa','otras empresas','Eulen (Grupo)','Madrid','88692','José Ramón Pérez Sancho','José Ramón','Pérez Sancho','CEO/Director','0000098')
;      